export { FBIcon } from './FBIcon'
export { IGIcon } from './IGIcon'
export { JJIcon } from './JJIcon'
export { TGIcon } from './TGIcon'
export { TVIcon } from './TVIcon'
export { VKIcon } from './VKIcon'
export { YUIcon } from './YUIcon'
